<?php

declare(strict_types=1);

namespace Sylapi\Courier\Enadawca;

use Sylapi\Courier\Abstracts\StatusTransformer;
use Sylapi\Courier\Enums\StatusType;

class EnadawcaStatusTransformer extends StatusTransformer
{
    /**
     * @var array<string, string>
     */
    public $statuses = [
        'A'          => StatusType::PROCESSING, //Próba doręczenia dokonana dzisiaj
        'B'          => StatusType::PROCESSING, //Próba doręczenia zostanie wykonana następnego dnia roboczego
        'C'          => StatusType::PROCESSING_FAILED, //Przesyłka zatrzymana, powiadomienie adresata w toku
        'D'          => StatusType::PROCESSING, //Nadawca został powiadomiony, oczekuje się na odpowiedź
        'E'          => StatusType::RETURNED, //Przesyłka zwrócona do nadawcy
        'G'          => StatusType::PROCESSING_FAILED, //Przesyłka zatrzymana do kontroli
        'P_A'        => StatusType::PICKUP_READY, //Awizo przesyłki
        'P_ADR'      => StatusType::PICKUP_READY, //Awizo - do ponownego doręczenia
        'P_ADRK'     => StatusType::PICKUP_READY, //Awizo - do ponownego doręczenia - korekta
        'P_AK'       => StatusType::PICKUP_READY, //Awizo przesyłki - korekta rezultatu
        'P_APP'      => StatusType::PICKUP_READY, //Awizo - po ponownej próbie doręczenia
        'P_APPK'     => StatusType::PICKUP_READY, //Awizo - po ponownej próbie doręczenia - korekta
        'P_AP_ZPO'   => StatusType::PICKUP_READY, //Pozostawienie w urzędzie przesyłki do przesł. na urząd awiz. ZPO
        'P_AR_ZPO'   => StatusType::PICKUP_READY, //Rozliczenie doręczyciela z przesyłki awizowanej w innym urz. ZPO
        'P_A_ZPO'    => StatusType::PICKUP_READY, //Awizo przesyłki ZPO
        'P_BRAKN'    => StatusType::PROCESSING_FAILED, //Brak nadania przesyłki zapowiedzianej w KN
        'P_CZDKN'    => StatusType::RETURNED, //Zwrot przesyłki do kraju nadania
        'P_D'        => StatusType::DELIVERED, //Doręczenie
        'P_DBR'      => StatusType::WAREHOUSE_ENTRY, //Rozpoczęcie procesu dystrybucji w placówce
        'P_DBZ'      => StatusType::WAREHOUSE_ENTRY, //Zakończenie procesu dystrybucji w placówce
        'P_DDLW_ZPO' => StatusType::WAREHOUSE_ENTRY, //Dołączenie przesyłki do ładunku wewnętrznego ZPO
        'P_DDL_ZPO'  => StatusType::WAREHOUSE_ENTRY, //Dołączenie przesyłki do ładunku ZPO
        'P_DDOZ_ZPO' => StatusType::WAREHOUSE_ENTRY, //Dołączenie przesyłki do opakowania zbiorczego ZPO
        'P_DDP'      => StatusType::WAREHOUSE_ENTRY, //Przesyłka dostarczona do Punktu
        'P_DDP_ZPO'  => StatusType::WAREHOUSE_ENTRY, //Przesyłka dostarczona do Punktu ZPO
        'P_DKAOD'    => StatusType::PROCESSING, //Dodanie do księgi awiz - oczekiwanie na doręczenie
        'P_DOAC'     => StatusType::PROCESSING, //Dostarczenie do Agencji Celnej
        'P_DOAC_A'   => StatusType::PROCESSING, //Dostarczenie do Agencji Celnej - anulowanie rezultatu
        'P_DOAC_K'   => StatusType::PROCESSING, //Dostarczenie do Agencji Celnej - korekta rezultatu
        'P_DS'       => StatusType::DELIVERED, //Doręczenie przesyłki do skrzynki oddawczej adresata
        'P_D_ZPO'    => StatusType::PICKUP_READY, //Doręczenie ZPO
        'P_KOD'      => StatusType::PROCESSING, //Wprowadzenie przesyłki do księgi oddawczej
        'P_KOD_ZPO'  => StatusType::PROCESSING, //Wprowadzenie przesyłki do księgi oddawczej ZPO
        'P_KOL'      => StatusType::PROCESSING, //Likwidacja księgi oddawczej po doręczeniu
        'P_KWD'      => StatusType::PROCESSING, //Wpis przesyłki do księgi wydanych
        'P_KWD_ZPO'  => StatusType::PROCESSING, //Wpis przesyłki do księgi wydanych ZPO
        'P_KZU_ZPO'  => StatusType::PROCESSING, //Wycofanie przesyłki z księgi zwrotów ZPO
        'P_MD_ZPO'   => StatusType::PROCESSING, //Modyfikacja danych przesyłki ZPO
        'P_NAD'      => StatusType::PROCESSING, //Nadanie
        'P_NAD_ZPO'  => StatusType::PROCESSING, //Nadanie ZPO
        'P_ND'       => StatusType::PROCESSING_FAILED, //Nieudane doręczenie
        'P_NDAC'     => StatusType::PROCESSING_FAILED, //Niedostarczenie do Agencji Celnej
        'P_NDAC_A'   => StatusType::PROCESSING_FAILED, //Niedostarczenie do Agencji Celnej - anulowanie rezultatu
        'P_NDAC_K'   => StatusType::PROCESSING_FAILED, //Niedostarczenie do Agencji Celnej - korekta rezultatu
        'P_NDB'      => StatusType::LOST, //Nieudane doręczenie - zaginięcie
        'P_NDB_ZPO'  => StatusType::LOST, //Nieudane doręczenie - zaginięcie ZPO
        'P_NDD'      => StatusType::RETURNING, //Nieudane doręczenie - decyzja o dosłaniu
        'P_NDD_ZPO'  => StatusType::RETURNING, //Nieudane doręczenie - decyzja o dosłaniu ZPO
        'P_NDK'      => StatusType::PICKUP_READY, //Nieudane doręczenie - korekta rezultatu
        'P_NDPD'     => StatusType::PICKUP_READY, //Nieudane doręczenie - kolejna próba dziś
        'P_NDPJ'     => StatusType::PICKUP_READY, //Nieudane doręczenie - kolejna próba jutro
        'P_NDPZ_ZPO' => StatusType::PROCESSING_FAILED, //Przesyłka niedostarczona do punktu ZPO
        'P_NDZ'      => StatusType::RETURNING, //Nieudane doręczenie - decyzja o zwrocie
        'P_NDZAP'    => StatusType::RETURNING, //Nieudane doręczenie - zatrzymana - adresat powiadomiony
        'P_NDZK'     => StatusType::RETURNING, //Nieudane doręczenie - decyzja o zwrocie - korekta rezultatu
        'P_NDZKON'   => StatusType::PROCESSING_FAILED, //Nieudane doręczenie - zatrzymana - do kontroli
        'P_ND_ZPO'   => StatusType::PROCESSING_FAILED, //Nieudane doręczenie ZPO
        'P_NDZ_ZPO'  => StatusType::RETURNING, //Nieudane doręczenie - decyzja o zwrocie ZPO
        'P_NM_ZPO'   => StatusType::PROCESSING, //Nadanie masowe ZPO
        'P_NOWU'     => StatusType::PROCESSING_FAILED, //Nieudane wydanie - do ponownego wydania
        'P_NPAC'     => StatusType::PROCESSING_FAILED, //Nieodebranie z Agencji Celnej
        'P_NPAC_A'   => StatusType::PROCESSING_FAILED, //Nieodebranie z Agencji Celnej - anulowanie rezultatu
        'P_NPAC_K'   => StatusType::PROCESSING_FAILED, //Nieodebranie z Agencji Celnej - korekta rezultatu
        'P_OWP'      => StatusType::DELIVERED, //Przesyłka odebrana w Punkcie
        'P_OWU'      => StatusType::DELIVERED, //Odebranie przesyłki w urzędzie
        'P_OWUK'     => StatusType::DELIVERED, //odebranie w urzędzie (korekta rezultatu)
        'P_OWUWPP'   => StatusType::DELIVERED, //Odebranie przesyłki w urzędzie wymiany (poczta przychodząca)
        'P_OWUWPW'   => StatusType::DELIVERED, //Odebranie przesyłki w urzędzie wymiany (poczta wychodząca)
        'P_OWU_ZPO'  => StatusType::WAREHOUSE_ENTRY, //Odebranie przesyłki w urzędzie ZPO
        'P_OZTW_ZPO' => StatusType::WAREHOUSE_ENTRY, //Odebranie przesyłki z transportu wewnętrznego ZPO
        'P_PA'       => StatusType::PICKUP_READY, //Ponowne awizo
        'P_PA_ZPO'   => StatusType::PICKUP_READY, //Ponowne awizo ZPO
        'P_PCP'      => StatusType::PROCESSING, //Przyjęcie przesyłki na cle - przywóz
        'P_PCWY'     => StatusType::PROCESSING, //Przekazanie przesyłki do cła - wywóz
        'P_PDLUC'    => StatusType::PROCESSING, //Przekazanie do lokalnego urzędu pocztowo-celnego
        'P_PKN'      => StatusType::PROCESSING_FAILED, //Nieudana próba kontaktu z adresatem przed doręczeniem
        'P_PKP'      => StatusType::WAREHOUSE_ENTRY, //Nawiązano kontakt z adresatem przed doręczeniem
        'P_POAC'     => StatusType::WAREHOUSE_ENTRY, //Odebranie z Agencji Celnej
        'P_POAC_A'   => StatusType::WAREHOUSE_ENTRY, //Odebranie z Agencji Celnej - anulowanie rezultatu
        'P_POAC_K'   => StatusType::WAREHOUSE_ENTRY, //Odebranie z Agencji Celnej - korekta rezultatu
        'P_POOE'     => StatusType::DELIVERED, //Powiadomienie email o odebraniu przesyłki
        'P_POOS'     => StatusType::DELIVERED, //Powiadomienie sms o odebraniu przesyłki
        'P_POWE'     => StatusType::PICKUP_READY, //Powiadomienie email o oczekiwaniu przesyłki w urzędzie
        'P_POWS'     => StatusType::PICKUP_READY, //Powiadomienie sms o oczekiwaniu przesyłki w urzędzie
        'P_POZE'     => StatusType::RETURNED, //Powiadomienie email o zwrocie przesyłki
        'P_POZS'     => StatusType::RETURNED, //Powiadomienie sms o zwrocie przesyłki
        'P_PWP'      => StatusType::PROCESSING, //Przesyłka przyjęta w punkcie
        'P_PZL'      => StatusType::PROCESSING, //Przyjęcie przesyłki z ładunkiem
        'P_PZL_ZPO'  => StatusType::PROCESSING, //Przyjęcie przesyłki z ładunkiem ZPO
        'P_R'        => StatusType::PROCESSING_FAILED, //Nieudane doręczenie - przechowywanie na życzenie
        'P_RDML'     => StatusType::PROCESSING, //Rozliczenie KD przez listonosza
        'P_REJ'      => StatusType::PROCESSING, //Rejestracja przesyłki
        'P_REJ_KN'   => StatusType::PROCESSING, //Rejestracja przesyłki z KN
        'P_ROZ_ZPO'  => StatusType::PROCESSING, //Rozliczenie przesyłki w dokumencie oddawczym ZPO
        'P_RUD'      => StatusType::PROCESSING, //Rejestracja przesyłki w urzędzie doręczenia
        'P_R_ZPO'    => StatusType::PROCESSING_FAILED, //Nieudane doręczenie - przechowywanie na życzenie ZPO
        'P_S'        => StatusType::DELIVERED, //P_S Pozostawienie przesyłki w skrytce
        'P_SCP'      => StatusType::PROCESSING, //Skierowanie przesyłki przez cło - przywóz
        'P_SDUNPK'   => StatusType::CANCELLED, //Skierowanie do urzędu niedoręczalnych przesyłek (korekta rez.)
        'P_SDUNPZPO' => StatusType::CANCELLED, //Skierowanie do urzędu niedoręczalnych przesyłek ZPO
        'P_S_ZPO'    => StatusType::APP_UNAVAILABLE, //Pozostawienie przesyłki w skrytce ZPO
        'P_UDO_ZPO'  => StatusType::PROCESSING, //Utworzenie przesyłki w placówce oddawczej - dok. oddawczy ZPO
        'P_UKEPO'    => StatusType::PROCESSING, //Udostępnienie karty EPO
        'P_URZ_ZPO'  => StatusType::PROCESSING, // Utworzenie przesyłki w placówce oddawczej rejest. zapleczowa ZPO
        'P_USZ'      => StatusType::PROCESSING_FAILED, //Uszkodzenie przesyłki
        'P_USZ_ZPO'  => StatusType::PROCESSING_FAILED, //Uszkodzenie przesyłki ZPO
        'P_WD'       => StatusType::PROCESSING, //Wydanie przesyłki doręczycielowi
        'P_WDUNP'    => StatusType::PROCESSING_FAILED, //Wejście przesyłki do urzędu niedoręczalnych przesyłek
        'P_WD_ZPO'   => StatusType::APP_UNAVAILABLE, //Wydanie przesyłki doręczycielowi ZPO
        'P_WEMAIL'   => StatusType::APP_UNAVAILABLE, //Wysłanie e-mail dla przesyłki
        'P_WEMAIL02' => StatusType::APP_UNAVAILABLE, //Powiadomienie e-mail o doręczeniu przes. do skrzynki pocztowej
        'P_WEOC'     => StatusType::PROCESSING, //Przyjęcie przesyłki w kraju przeznaczenia
        'P_WEPL'     => StatusType::PROCESSING, //Przyjęcie przesyłki w Polsce
        'P_WFAX'     => StatusType::PROCESSING, //Wysłanie faksu dla przesyłki
        'P_WMU_ZPO'  => StatusType::PROCESSING, //Usunięcie mylnego wpisu przesyłki ZPO
        'P_WM_ZPO'   => StatusType::PROCESSING, //Mylny wpis przesyłki ZPO
        'P_WN2'      => StatusType::PROCESSING_FAILED, //Negatywna weryfikacja przesyłki proceduralnej w jedn. oddawczej
        'P_WN3'      => StatusType::PROCESSING_FAILED, //Negatywna weryfikacja przesyłki proceduralnej w DOK
        'P_WP2'      => StatusType::PROCESSING, //Pozytywna weryfikacja przesyłki proceduralnej w jedn. oddawczej
        'P_WP3'      => StatusType::PROCESSING, //Pozytywna weryfikacja przesyłki proceduralnej w DOK
        'P_WPUCPP'   => StatusType::PROCESSING, //Zwolnienie przesyłki przez urząd celny (poczta przychodząca)
        'P_WPUCWKP'  => StatusType::PROCESSING, //Zwolnienie przesyłki przez urząd celny w kraju przeznaczenia
        'P_WSMS'     => StatusType::PROCESSING, //Wysłanie SMS dla przesyłki
        'P_WSMS02'   => StatusType::PROCESSING, //Powiadomienie SMS o doręczeniu przesyłki do skrzynki pocztowej
        'P_WUPD'     => StatusType::PROCESSING, //Wydanie przesyłki uprawnionemu do odbioru
        'P_WVOICE'   => StatusType::PROCESSING, //Powiadomienie głosowe dla przesyłki
        'P_WYOC'     => StatusType::PROCESSING, //Wysłanie przesyłki z kraju nadania
        'P_WYPL'     => StatusType::PROCESSING, //Wysłanie przesyłki z Polski
        'P_WZL'      => StatusType::PROCESSING,  //Wysłanie przesyłki z ładunkiem
        'P_WZL_ZPO'  => StatusType::PROCESSING, //Wysłanie przesyłki z ładunkiem ZPO
        'P_WZOZ_ZPO' => StatusType::PROCESSING, //Wyciągnięcie przesyłki z opakowania zbiorczego ZPO
        'P_Z'        => StatusType::PROCESSING, //Załadunek przesyłki
        'P_ZAG'      => StatusType::LOST, //Zaginięcie przesyłki
        'P_ZAG_ZPO'  => StatusType::LOST, //Zaginięcie przesyłki ZPO
        'P_ZDD'      => StatusType::PROCESSING, //Zmiana danych doręczenia
        'P_ZDUN'     => StatusType::RETURNED, //Zwrot przesyłki do urzędu nadania
        'P_ZDUN_ZPO' => StatusType::RETURNING, //Zwrot przesyłki do urzędu nadania ZPO
        'P_ZKK'      => StatusType::PROCESSING, //Zmiana kanału komunikacji
        'P_ZKK_ZPO'  => StatusType::PROCESSING, //Zmiana kanału komunikacji ZPO
        'P_ZNISZ'    => StatusType::LOST, //Przesyłka uległa zniszczeniu w wyniku pożaru
        'P_ZPD'      => StatusType::PROCESSING, //Doręczenie na życzenie - do ponownego doręczenia
        'P_ZPNA'     => StatusType::RETURNING, //Doręczenie na życzenie - przesyłka dosłana
        'P_ZPNP'     => StatusType::PROCESSING_FAILED, //Doręczenie na życzenie - nieudana próba doręczenia
        'P_ZPO'      => StatusType::PROCESSING, //Nadanie zwrotnego potwierdzenia odbioru
        'P_ZPUCPP'   => StatusType::PROCESSING_FAILED, //Zatrzymanie przesyłki przez urząd celny (poczta przychodząca)
        'P_ZPUCWKP'  => StatusType::PROCESSING_FAILED, //Zatrzymanie przesyłki przez urząd celny w kraju przeznaczenia
        'P_ZPWM'     => StatusType::PROCESSING, //Doręczenie na życzenie - wydanie z magazynu
        'P_ZWC'      => StatusType::PROCESSING, //Zatrzymanie przesyłki w cle
        'P_ZWMC'     => StatusType::PROCESSING, //Zatrzymanie przesyłki w magazynie celnym
        'P_ZZC'      => StatusType::PROCESSING, //Zwrot przesyłki z cła
        'P_ZZPZ'     => StatusType::PROCESSING_FAILED, //Przesyłka nieodebrana w punkcie
    ];
}
